# Site settings
author: exuberant-computer-4170
title: 
header-img: img/home-bg.png
email: dariusmoody61@gmail.com
copyright_name: exuberant-computer-4170
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  falisu62

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
